"use client";

import Link from "next/link";
import { usePathname, useRouter } from "next/navigation";
import { useState } from "react";
import { Bell, CandlestickChart, ChevronDown, CircleHelp, LayoutDashboard, LogOut, Menu, Search, Settings2, Trophy, WalletCards, X, Zap } from "lucide-react";
import { cn, initials } from "@/lib/utils";
import { Badge } from "@/components/ui";

const navGroups = [
  { label: "Workspace", items: [{ href: "/dashboard", label: "Overview", icon: LayoutDashboard }, { href: "/terminal", label: "Terminal", icon: CandlestickChart }, { href: "/markets", label: "Markets", icon: Search }, { href: "/portfolio", label: "Portfolio", icon: WalletCards }, { href: "/futures", label: "Futures", icon: CandlestickChart }] },
  { label: "Compete", items: [{ href: "/leaderboards", label: "Leaderboards", icon: Trophy }, { href: "/challenges", label: "Challenges", icon: Zap }] },
  { label: "Account", items: [{ href: "/settings", label: "Settings", icon: Settings2 }, { href: "/help", label: "How it works", icon: CircleHelp }] },
];

export function AppShell({ user, children }: { user: { username: string; role: string }; children: React.ReactNode }) {
  const pathname = usePathname(); const router = useRouter(); const [mobileOpen, setMobileOpen] = useState(false); const [loggingOut, setLoggingOut] = useState(false);
  async function logout() { setLoggingOut(true); await fetch("/api/auth/logout", { method: "POST" }); router.push("/"); router.refresh(); }
  return <div className="min-h-screen bg-[var(--bg)]">
    <aside className={cn("fixed inset-y-0 left-0 z-50 flex w-[248px] flex-col border-r border-white/[.07] bg-[#0b0e14]/95 px-4 py-5 backdrop-blur-2xl transition-transform lg:translate-x-0", mobileOpen ? "translate-x-0" : "-translate-x-full")}>
      <div className="flex items-center justify-between px-2 pb-8"><Link href="/dashboard" className="flex items-center gap-3" onClick={() => setMobileOpen(false)}><span className="flex h-8 w-8 items-center justify-center rounded-[10px] bg-[var(--accent)] text-sm font-black text-white shadow-[0_8px_24px_rgba(139,140,255,.35)]">A</span><span className="text-[13px] font-bold tracking-[.15em] text-white">ALPHA<span className="text-[var(--accent-bright)]">/</span>TERMINAL</span></Link><button className="rounded-lg p-2 text-[var(--muted)] lg:hidden" onClick={() => setMobileOpen(false)}><X size={17} /></button></div>
      <div className="mb-6 rounded-xl border border-[var(--accent)]/20 bg-[var(--accent)]/[.07] p-3"><div className="flex items-center justify-between"><span className="text-[10px] font-bold uppercase tracking-[.14em] text-[var(--accent-bright)]">Simulation mode</span><span className="h-1.5 w-1.5 rounded-full bg-[var(--positive)] shadow-[0_0_10px_var(--positive)]" /></div><p className="mt-2 text-xs leading-5 text-[var(--muted)]">All balances are virtual. Markets are sourced from public data.</p></div>
      <nav className="flex-1 space-y-7 overflow-y-auto">{navGroups.map(group => <div key={group.label}><div className="mb-2 px-3 text-[10px] font-semibold uppercase tracking-[.18em] text-[#566174]">{group.label}</div><div className="space-y-1">{group.items.map(item => { const Icon = item.icon; const active = pathname === item.href || item.href !== "/dashboard" && pathname.startsWith(item.href); return <Link href={item.href} key={item.href} onClick={() => setMobileOpen(false)} className={cn("group flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm transition-colors", active ? "bg-white/[.09] text-white" : "text-[var(--muted)] hover:bg-white/[.05] hover:text-[var(--muted-strong)]")}><Icon size={17} strokeWidth={active ? 2.2 : 1.8} className={active ? "text-[var(--accent-bright)]" : "text-[#647086]"} /><span>{item.label}</span>{item.href === "/terminal" && <Badge tone="accent" className="ml-auto px-1.5 py-0.5 text-[8px]">Live</Badge>}</Link>; })}</div></div>)}</nav>
      <div className="mt-5 border-t border-white/[.07] pt-4"><div className="flex items-center gap-3 rounded-xl p-2"><div className="flex h-9 w-9 items-center justify-center rounded-full bg-gradient-to-br from-[#7475df] to-[#54bad9] text-xs font-bold text-white">{initials(user.username)}</div><div className="min-w-0 flex-1"><div className="truncate text-sm font-semibold text-white">{user.username}</div><div className="text-[11px] text-[var(--muted)]">Paper trader</div></div><button title="Log out" disabled={loggingOut} onClick={logout} className="rounded-lg p-2 text-[var(--muted)] hover:bg-white/[.06] hover:text-white"><LogOut size={16} /></button></div></div>
    </aside>
    {mobileOpen && <button aria-label="Close navigation" className="fixed inset-0 z-40 bg-black/60 lg:hidden" onClick={() => setMobileOpen(false)} />}
    <main className="lg:pl-[248px]"><header className="sticky top-0 z-30 flex h-[68px] items-center justify-between border-b border-white/[.07] bg-[var(--bg)]/80 px-4 backdrop-blur-xl md:px-8"><div className="flex items-center gap-3"><button className="rounded-xl border border-white/[.08] p-2 text-[var(--muted)] lg:hidden" onClick={() => setMobileOpen(true)}><Menu size={18} /></button><div className="hidden items-center gap-2 text-xs text-[var(--muted)] sm:flex"><span className="h-1.5 w-1.5 rounded-full bg-[var(--positive)] live-dot" />Markets open <span className="text-[#566174]">/</span> <span className="text-[var(--muted-strong)]">Public data feed</span></div></div><div className="flex items-center gap-2"><Link href="/terminal" className="hidden items-center gap-2 rounded-xl bg-white/[.06] px-3 py-2 text-xs font-medium text-[var(--muted-strong)] hover:bg-white/[.1] sm:flex"><Zap size={14} className="text-[var(--accent-bright)]" />Quick trade <kbd className="ml-2 rounded bg-black/30 px-1.5 py-0.5 text-[9px] text-[#68748a]">⌘K</kbd></Link><Link href="/notifications" aria-label="Notifications" className="relative rounded-xl p-2.5 text-[var(--muted)] hover:bg-white/[.06] hover:text-white"><Bell size={18} /><span className="absolute right-2 top-2 h-1.5 w-1.5 rounded-full bg-[var(--accent-bright)]" /></Link><Link href="/settings" className="flex items-center gap-2 rounded-xl p-1.5 hover:bg-white/[.06]"><div className="flex h-7 w-7 items-center justify-center rounded-full bg-gradient-to-br from-[#7475df] to-[#54bad9] text-[10px] font-bold">{initials(user.username)}</div><ChevronDown size={14} className="text-[var(--muted)]" /></Link></div></header><div className="mx-auto max-w-[1600px] px-4 py-7 md:px-8 lg:px-10">{children}</div></main>
  </div>;
}
