"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { Award, CalendarDays, ChevronRight, ShieldCheck, Sparkles, Trophy, Users, Zap } from "lucide-react";
import { Badge, Button, Card, SectionHeading, Skeleton } from "@/components/ui";
import { formatCurrency, formatPercent } from "@/lib/format";

type Leader = { rank: number; username: string; avatarUrl: string | null; returnPercentage: string; realizedPnl: string; tradeCount: number; winRate: string; achievements: string[] };
type Challenge = { id: string; name: string; description: string; startingCapital: string; startTime: string; endTime: string; status: string; participants: number; joined: boolean; accountScope: string | null; configuration: Record<string, unknown> };

export function LeaderboardsClient() {
  const [entries, setEntries] = useState<Leader[]>([]); const [type, setType] = useState("all-time"); const [loading, setLoading] = useState(true);
  useEffect(() => { setLoading(true); fetch(`/api/leaderboards?type=${type}`).then(r => r.json()).then(body => { setEntries(body.data?.entries ?? []); setLoading(false); }); }, [type]);
  return <div className="animate-slide-up"><SectionHeading eyebrow="Competitive edge" title="Leaderboards" description="Compare normalized simulated performance. Starting balance never determines rank." action={<Badge tone="accent"><Trophy size={12} className="mr-1" /> Server-ranked</Badge>} /><div className="mb-5 flex gap-1 overflow-x-auto">{[["all-time", "All time"], ["realized", "Realized P&L"], ["win-rate", "Win rate"]].map(([value, label]) => <button key={value} onClick={() => setType(value)} className={`whitespace-nowrap rounded-xl px-4 py-2.5 text-xs font-semibold ${type === value ? "bg-[var(--accent)]/15 text-[var(--accent-bright)]" : "text-[var(--muted)] hover:bg-white/[.05]"}`}>{label}</button>)}</div><Card className="overflow-hidden"><div className="grid grid-cols-[56px_1.6fr_1fr_1fr_1fr] border-b border-white/[.06] px-5 py-3 text-[10px] uppercase tracking-[.15em] text-[#657187]"><span>Rank</span><span>Trader</span><span>Return</span><span>Realized P&L</span><span className="text-right">Win rate</span></div>{loading ? <div className="space-y-3 p-5">{[1,2,3,4].map(i => <Skeleton key={i} className="h-16" />)}</div> : entries.length ? <div className="divide-y divide-white/[.05]">{entries.map((entry) => <div key={entry.username} className="grid grid-cols-[56px_1.6fr_1fr_1fr_1fr] items-center px-5 py-4"><div className={`text-sm font-bold ${entry.rank <= 3 ? "text-amber-300" : "text-[var(--muted)]"}`}>{entry.rank < 10 ? `0${entry.rank}` : entry.rank}</div><div className="flex items-center gap-3"><div className="flex h-9 w-9 items-center justify-center rounded-full bg-gradient-to-br from-[#7475df] to-[#54bad9] text-[10px] font-bold text-white">{entry.username.slice(0, 2).toUpperCase()}</div><div><div className="text-sm font-semibold text-white">{entry.username}</div><div className="mt-1 flex gap-1">{entry.achievements.slice(0, 2).map(a => <span key={a} title={a}><Award size={12} className="text-[var(--accent-bright)]" /></span>)}</div></div></div><div className={`tabular text-sm font-semibold ${Number(entry.returnPercentage) >= 0 ? "text-[var(--positive)]" : "text-[var(--negative)]"}`}>{formatPercent(entry.returnPercentage)}</div><div className="tabular text-sm text-[var(--muted-strong)]">{formatCurrency(entry.realizedPnl)}</div><div className="tabular text-right text-sm text-[var(--muted-strong)]">{entry.winRate}%<div className="mt-1 text-[10px] text-[#657187]">{entry.tradeCount} trades</div></div></div>)}</div> : <div className="p-16 text-center text-sm text-[var(--muted)]">No public trader records yet. Make the first move.</div>}<div className="border-t border-white/[.05] px-5 py-3 text-[10px] leading-5 text-[#657187]">Rankings use server-side portfolio valuations and exclude users who opted out of public profiles. Win rate is not a profitability guarantee.</div></Card></div>;
}

export function ChallengesClient() {
  const [rows, setRows] = useState<Challenge[]>([]); const [loading, setLoading] = useState(true); const [message, setMessage] = useState("");
  async function load() { const response = await fetch("/api/challenges"); const body = await response.json(); setRows(body.data?.challenges ?? []); setLoading(false); }
  useEffect(() => { load(); }, []);
  async function join(id: string) { const response = await fetch(`/api/challenges/${id}/join`, { method: "POST" }); const body = await response.json(); setMessage(response.ok ? "Challenge account created. Open Futures/Terminal to trade it." : body.error?.message ?? "Unable to join challenge."); if (response.ok) load(); }
  return <div className="animate-slide-up"><SectionHeading eyebrow="Practice with a clock" title="Challenges" description="Structured simulations with fixed rules, fixed starting snapshots, and transparent ranking." action={<Badge tone="positive"><Sparkles size={12} className="mr-1" />Virtual funds only</Badge>} />{message && <div className="mb-5 rounded-xl border border-[var(--accent)]/20 bg-[var(--accent)]/10 px-4 py-3 text-xs text-[var(--accent-bright)]">{message}</div>}{loading ? <div className="grid gap-4 md:grid-cols-2">{[1,2].map(i => <Skeleton key={i} className="h-52" />)}</div> : <div className="grid gap-4 md:grid-cols-2">{rows.map(challenge => <Card key={challenge.id} className="p-5"><div className="flex items-start justify-between"><div className="flex h-11 w-11 items-center justify-center rounded-xl bg-[var(--accent)]/12 text-[var(--accent-bright)]"><Zap size={20} /></div><Badge tone={challenge.status === "ACTIVE" ? "positive" : "neutral"}>{challenge.status}</Badge></div><h2 className="mt-6 text-lg font-semibold tracking-[-.03em] text-white">{challenge.name}</h2><p className="mt-2 text-sm leading-6 text-[var(--muted)]">{challenge.description}</p><div className="mt-6 grid grid-cols-3 gap-3 border-y border-white/[.06] py-4 text-xs"><div><div className="text-[var(--muted)]">Starting</div><div className="mt-1 tabular font-semibold text-white">{formatCurrency(challenge.startingCapital)}</div></div><div><div className="text-[var(--muted)]">Traders</div><div className="mt-1 flex items-center gap-1 font-semibold text-white"><Users size={13} />{challenge.participants}</div></div><div><div className="text-[var(--muted)]">Ends</div><div className="mt-1 font-semibold text-white">{new Date(challenge.endTime).toLocaleDateString(undefined, { month: "short", day: "numeric" })}</div></div></div><div className="mt-5 flex items-center justify-between"><div className="flex items-center gap-2 text-[10px] text-[var(--muted)]"><ShieldCheck size={13} className="text-[var(--positive)]" />Max leverage {String(challenge.configuration.maxLeverage ?? 1)}x</div>{challenge.joined ? <Link href={`/terminal?scope=${encodeURIComponent(challenge.accountScope ?? challenge.id)}`}><Button variant="secondary">Trade challenge <ChevronRight size={14} /></Button></Link> : <Button onClick={() => join(challenge.id)}>Join challenge <ChevronRight size={14} /></Button>}</div></Card>)}{!rows.length && <Card className="p-16 text-center md:col-span-2"><CalendarDays size={26} className="mx-auto mb-4 text-[#657187]" /><div className="text-sm font-semibold text-white">No active challenges</div><p className="mt-2 text-xs text-[var(--muted)]">A new simulation season will appear here when it opens.</p></Card>}</div>}</div>;
}
